import { Game } from '@/types/game';

export const sampleGames: Game[] = [
  // {
  //   id: '1',
  //   title: 'Find the Vampire',
  //   description:
  //     'Embark on a thrilling vampire hunting adventure! As a skilled hunter, use your X-ray vision machine to identify bloodsuckers hiding among ordinary people. Each level brings new challenges as vampires become more cunning in their disguises. With special exterminator kits and detectors, your mission is to save the city from a vampire uprising.',
  //   thumbnailUrl: 'https://placehold.co/600x400/png',
  //   gameUrl: 'https://www.crazygames.com/game/find-the-vampire',
  //   category: 'action',
  //   tags: ['action', 'vampire', 'hunting', 'strategy'],
  //   rating: 4.8,
  //   playCount: 69676,
  //   createdAt: '2024-03-19',
  //   updatedAt: '2024-03-19',
  // },
  // {
  //   id: '2',
  //   title: 'Vampire Racing Night',
  //   description:
  //     'Race through dark, gothic streets in this unique vampire-themed racing game. Choose from a collection of supernatural vehicles, each with its own dark powers. Challenge other vampires in high-speed pursuits through misty Victorian cities and haunted highways. Can you become the fastest vampire in the night?',
  //   thumbnailUrl: 'https://placehold.co/600x400/png',
  //   gameUrl: 'https://www.crazygames.com/game/find-the-vampire',
  //   category: 'racing',
  //   tags: ['racing', 'vampire', 'night', 'speed'],
  //   rating: 4.6,
  //   playCount: 45000,
  //   createdAt: '2024-03-01',
  //   updatedAt: '2024-03-19',
  // },
  // {
  //   id: '3',
  //   title: 'Vampire Hunter: Action RPG',
  //   description:
  //     'Step into the shoes of an elite vampire hunter in this action-packed RPG. Upgrade your weapons and skills as you track down powerful vampire lords. Explore gothic castles, ancient crypts, and cursed villages. With intense combat mechanics and a deep storyline, every mission brings you closer to the ultimate vampire showdown.',
  //   thumbnailUrl: 'https://placehold.co/600x400/png',
  //   gameUrl: 'https://www.crazygames.com/game/find-the-vampire',
  //   category: 'action',
  //   tags: ['action', 'rpg', 'vampire', 'combat'],
  //   rating: 4.9,
  //   playCount: 58000,
  //   createdAt: '2024-02-15',
  //   updatedAt: '2024-03-19',
  // },
  // {
  //   id: '4',
  //   title: 'Vampire Drift Masters',
  //   description:
  //     'Master the art of supernatural drifting in this thrilling racing game. Control powerful vehicles enhanced with vampire magic, drift through challenging tracks filled with obstacles and supernatural hazards. Compete against other vampire racers, unlock new cars with unique abilities, and prove yourself as the ultimate drift master of the night.',
  //   thumbnailUrl: 'https://placehold.co/600x400/png',
  //   gameUrl: 'https://www.crazygames.com/game/find-the-vampire',
  //   category: 'racing',
  //   tags: ['racing', 'drift', 'vampire', 'competition'],
  //   rating: 4.7,
  //   playCount: 42000,
  //   createdAt: '2024-02-28',
  //   updatedAt: '2024-03-19',
  // },
  {
    id: '1',
    title: 'Find the Vampire',
    description:
      'Embark on a thrilling vampire hunting adventure! As a skilled hunter, use your X-ray vision machine to identify bloodsuckers hiding among ordinary people. Each level brings new challenges as vampires become more cunning in their disguises. With special exterminator kits and detectors, your mission is to save the city from a vampire uprising.',
    thumbnailUrl: 'https://placehold.co/600x400/png',
    gameUrl: 'https://itch.io/embed-upload/8661729?color=333333',
    category: 'action',
    tags: ['action', 'vampire', 'hunting', 'strategy'],
    rating: 4.8,
    playCount: 69676,
    createdAt: '2024-03-19',
    updatedAt: '2024-03-19',
  },
  {
    id: '2',
    title: 'Vampire Racing Night',
    description:
      'Race through dark, gothic streets in this unique vampire-themed racing game. Choose from a collection of supernatural vehicles, each with its own dark powers. Challenge other vampires in high-speed pursuits through misty Victorian cities and haunted highways. Can you become the fastest vampire in the night?',
    thumbnailUrl: 'https://placehold.co/600x400/png',
    gameUrl: 'https://games.construct.net/937/latest',
    category: 'racing',
    tags: ['racing', 'vampire', 'night', 'speed'],
    rating: 4.6,
    playCount: 45000,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-19',
  },
  {
    id: '3',
    title: 'Vampire Hunter: Action RPG',
    description:
      'Step into the shoes of an elite vampire hunter in this action-packed RPG. Upgrade your weapons and skills as you track down powerful vampire lords. Explore gothic castles, ancient crypts, and cursed villages. With intense combat mechanics and a deep storyline, every mission brings you closer to the ultimate vampire showdown.',
    thumbnailUrl: 'https://placehold.co/600x400/png',
    gameUrl: 'https://v6p9d9t4.ssl.hwcdn.net/html/6581711/index.html',
    category: 'action',
    tags: ['action', 'rpg', 'vampire', 'combat'],
    rating: 4.9,
    playCount: 58000,
    createdAt: '2024-02-15',
    updatedAt: '2024-03-19',
  },
  {
    id: '4',
    title: 'Vampire Drift Masters',
    description:
      'Master the art of supernatural drifting in this thrilling racing game. Control powerful vehicles enhanced with vampire magic, drift through challenging tracks filled with obstacles and supernatural hazards. Compete against other vampire racers, unlock new cars with unique abilities, and prove yourself as the ultimate drift master of the night.',
    thumbnailUrl: 'https://placehold.co/600x400/png',
    gameUrl:
      'https://html5.gamedistribution.com/rvvASMiM/f804d079d19f43d19522c49740de5b34/',
    category: 'racing',
    tags: ['racing', 'drift', 'vampire', 'competition'],
    rating: 4.7,
    playCount: 42000,
    createdAt: '2024-02-28',
    updatedAt: '2024-03-19',
  },
  {
    id: '5',
    title: 'Find the Vampire',
    description:
      'Embark on a thrilling vampire hunting adventure! As a skilled hunter, use your X-ray vision machine to identify bloodsuckers hiding among ordinary people. Each level brings new challenges as vampires become more cunning in their disguises. With special exterminator kits and detectors, your mission is to save the city from a vampire uprising.',
    thumbnailUrl: 'https://placehold.co/600x400/png',
    gameUrl: 'https://www.crazygames.com/game/find-the-vampire',
    category: 'action',
    tags: ['action', 'vampire', 'hunting', 'strategy'],
    rating: 4.8,
    playCount: 69676,
    createdAt: '2024-03-19',
    updatedAt: '2024-03-19',
  },
];
